### ISSUE TITLE
Fix testing against multiple Python versions

### ISSUE THREAD

**Issue by kskyten** [HIIT/elfi#38]
The tox virtual environments need to be setup so that tests can be run against different Python interpreters. Currently the problem seems to be that GPy can't be installed directly from pip without first installing numpy.

**Comment by vuolleko** [comment]
Bump.

**Comment by kskyten** [comment]
Testing against python 2 should work by adding a line tot `.travis.yml`. However the code is not currently compatible. We should see how much additional work adding and maintaining bakwards compatibility would require. This is a separate issue however.
